-- MySQL Script generated by MySQL Workbench
-- Sun 30 Oct 2016 02:18:51 PM MDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Grocery List`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Grocery List` (
  `id_grocery` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `cost` VARCHAR(45) NULL,
  PRIMARY KEY (`id_grocery`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Current_Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Current_Inventory` (
  `id_inventory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `inv_quantity` VARCHAR(45) NULL,
  `expire_date` VARCHAR(45) NULL,
  PRIMARY KEY (`id_inventory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipie Consortium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipie Consortium` (
  `id_Recipie` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `style` VARCHAR(45) NULL,
  `Ingredients` VARCHAR(45) NULL,
  `approx. cost` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Recipie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `category_id`  NOT NULL,
  `name` (255) NOT NULL,
  PRIMARY KEY (`category_id`));

USE `mydb` ;

-- -----------------------------------------------------
-- Placeholder table for view `mydb`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`view1` (`id` INT);

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
$$

DELIMITER ;

-- -----------------------------------------------------
-- View `mydb`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`view1`;
USE `mydb`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
